
#
# Makefile for util-test
#

NAME            := util-test
LIBDIR          := ../..

INCLUDE         := -I.\
                   -I./include\
                   -I../include\
                   -I$(LIBDIR)/include\
                   -I$(LIBDIR)/lpc23xx-pll/include\
                   -I$(LIBDIR)/lpc23xx-util/include\
                   -I$(LIBDIR)/lpc23xx-timer/include\
                   -I$(LIBDIR)/lpc23xx-uart/include

DEBUG           = -DDEBUG_UTIL

include $(LIBDIR)/include/common-test-make.mk
