
#
# Makefile for adc-test
#

NAME            := adc-test
LIBDIR          := ../..

INCLUDE         := -I.\
                   -I./include\
                   -I../include\
                   -I$(LIBDIR)/include\
                   -I$(LIBDIR)/lpc23xx-mam/include\
                   -I$(LIBDIR)/lpc23xx-pll/include\
                   -I$(LIBDIR)/lpc23xx-util/include\
                   -I$(LIBDIR)/lpc23xx-uart/include

#LPC23XX_PART    = LPC2378
#DEBUG           = -DDEBUG_ADC

include $(LIBDIR)/include/common-test-make.mk
