
NAME            := lpc23xx-binsem-test
LIBDIR          := ../..

INCLUDE         := -I.\
                   -I./include\
                   -I../include\
                   -I$(LIBDIR)/include\
                   -I$(LIBDIR)/lpc23xx-pll/include\
                   -I$(LIBDIR)/lpc23xx-uart/include\
                   -I$(LIBDIR)/lpc23xx-binsem/include


include $(LIBDIR)/include/common-test-make.mk
