
#
# Makefile for lpc23xx-pll-test
#

NAME            := lpc23xx-pll-test
LIBDIR          := ../..
INCLUDE         := -I.\
                   -I./include\
                   -I../include\
                   -I$(LIBDIR)/include


include $(LIBDIR)/include/common-test-make.mk

